// Package conf generates the bitbake build configuration — local.conf and
// bblayers.conf — that kas would otherwise write. Paths are emitted for the
// container's view: the project bind-mounts to WorkDir and the cache mounts at
// its host path, so the two agree.
package conf

import (
	"fmt"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"github.com/haonguy3n/yb/internal/config"
)

// WorkDir is where the project tree is bind-mounted inside the container.
const WorkDir = "/work"

// BuildDir is the bitbake build directory inside the container.
var BuildDir = path.Join(WorkDir, "build")

// LocalConf renders build/conf/local.conf. dlDir and sstateDir become DL_DIR
// and SSTATE_DIR (they are mounted into the container at the same host path).
func LocalConf(c *config.Config, dlDir, sstateDir string, nproc int) string {
	var b strings.Builder
	b.WriteString("# Generated by yb — do not edit.\n\n")

	keys := make([]string, 0, len(c.LocalConfHeader))
	for k := range c.LocalConfHeader {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		b.WriteString(strings.TrimRight(c.LocalConfHeader[k], "\n"))
		b.WriteString("\n")
	}

	fmt.Fprintf(&b, "\nMACHINE ??= %q\n", c.Machine)
	fmt.Fprintf(&b, "DISTRO ??= %q\n", c.Distro)
	fmt.Fprintf(&b, "DL_DIR ?= %q\n", dlDir)
	fmt.Fprintf(&b, "SSTATE_DIR ?= %q\n", sstateDir)
	fmt.Fprintf(&b, "BB_NUMBER_THREADS ??= %q\n", fmt.Sprint(nproc))
	fmt.Fprintf(&b, "PARALLEL_MAKE ??= %q\n", fmt.Sprintf("-j %d", nproc))
	return b.String()
}

// BBLayers renders build/conf/bblayers.conf from the config's resolved layers,
// as absolute container paths under WorkDir.
func BBLayers(c *config.Config) string {
	var b strings.Builder
	b.WriteString("# Generated by yb — do not edit.\n")
	b.WriteString("POKY_BBLAYERS_CONF_VERSION = \"2\"\n")
	b.WriteString("BBPATH = \"${TOPDIR}\"\n")
	b.WriteString("BBFILES ?= \"\"\n")
	b.WriteString("BBLAYERS ?= \" \\\n")
	for _, rel := range c.Layers() {
		fmt.Fprintf(&b, "  %s \\\n", path.Join(WorkDir, filepath.ToSlash(rel)))
	}
	b.WriteString("\"\n")
	return b.String()
}

// Write writes both confs into hostBuildDir/conf, creating it if needed.
func Write(hostBuildDir, localConf, bblayers string) error {
	confDir := filepath.Join(hostBuildDir, "conf")
	if err := os.MkdirAll(confDir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(confDir, "local.conf"), []byte(localConf), 0o644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(confDir, "bblayers.conf"), []byte(bblayers), 0o644)
}
